<a href="https://colab.research.google.com/github/kxrrym03/Porsche-Stock-Data/blob/main/Porsche_Stock_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
from google.colab import files
uploaded = files.upload()

Saving porsche_stock_data.csv to porsche_stock_data.csv

In [4]:
df = pd.read_csv('porsche_stock_data.csv')
df.shape

(866, 6)

In [5]:
df.head()

         date       open       high        low      close   volume
0  2022-09-30  75.617410  76.164700  75.252548  75.252548  5079137
1  2022-10-03  75.252548  75.453222  73.884320  74.614044  2403446
2  2022-10-04  75.434974  79.795067  74.796470  79.795067  1599630
3  2022-10-05  79.448447  81.765314  78.919397  80.196411  1321304
4  2022-10-06  81.820036  85.468644  81.491661  82.750435  2217065

In [6]:
df.tail()

           date       open       high        low      close  volume
861  2026-02-19  42.000000  42.400002  41.130001  41.700001  402139
862  2026-02-20  41.400002  43.049999  41.400002  42.340000  893498
863  2026-02-23  42.169998  42.360001  40.959999  41.169998  761838
864  2026-02-24  41.200001  42.230000  41.180000  41.549999  712492
865  2026-02-25  41.490002  41.849998  41.029999  41.320000  411145

In [7]:
df.isnull().sum()

date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 866 entries, 0 to 865
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    866 non-null    object
 1   open    866 non-null    float64
 2   high    866 non-null    float64
 3   low     866 non-null    float64
 4   close   866 non-null    float64
 5   volume  866 non-null    int64
dtypes: float64(4), int64(1), object(1)
memory usage: 40.7+ KB

In [10]:
df.describe()

             open        high         low       close        volume
count  866.000000  866.000000  866.000000  866.000000  8.660000e+02
mean    70.638938   71.434490   69.723691   70.532747  5.674776e+05
std     21.944210   22.131165   21.628439   21.899780  5.673197e+05
min     39.120645   40.029999   38.398831   39.529999  0.000000e+00
25%     46.747500   47.462501   46.304999   46.809999  3.100342e+05
50%     69.151123   69.721450   67.679951   68.686703  4.584455e+05
75%     88.536388   90.211843   86.928254   88.216194  6.722385e+05
max    109.868710  110.187969  108.728520  109.777496  9.901667e+06

In [11]:
df.dtypes

date       object
open      float64
high      float64
low       float64
close     float64
volume      int64
dtype: object

In [12]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume'], dtype='object')

## Visualizations